/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        'empower-coral': '#FF7F50',
        'empower-lilac': '#C8A2C8',
        'empower-navy': '#1C1F4C',
        'empower-light-gray': '#E8E8E8',
        'empower-mid-gray': '#8C8C8C',
        'empower-dark-gray': '#525252',
      },
      fontFamily: {
        'heading': ['Sports Invation', 'sans-serif'],
        'body': ['Balegare', 'system-ui', 'sans-serif'],
      },
    },
  },
  safelist: [
    'bg-gradient-to-br',
    'bg-gradient-to-r',
    'bg-gradient-to-b',
    'from-empower-coral',
    'to-empower-lilac',
    'from-empower-lilac',
    'to-empower-coral',
    'from-empower-navy',
    'to-empower-navy',
    'bg-empower-coral',
    'bg-empower-lilac',
    'bg-empower-navy',
    'bg-empower-light-gray',
    'bg-empower-mid-gray',
    'bg-empower-dark-gray',
    'text-empower-coral',
    'text-empower-lilac',
    'text-empower-navy',
    'text-empower-light-gray',
    'text-empower-mid-gray',
    'text-empower-dark-gray',
    'section-gradient',
    'section-navy',
    'card-gradient',
    'btn-primary',
    'btn-secondary',
    'btn-outline',
    'text-gradient',
    'gradient-coral',
    'gradient-lilac',
    'gradient-navy',
    'gradient-hero',
    'glass',
    'glass-dark',
  ],
} 