/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        'empower-coral': '#FF7F50',
        'empower-lilac': '#C8A2C8',
        'empower-navy': '#1C1F4C',
        'empower-light-gray': '#E8E8E8',
        'empower-mid-gray': '#8C8C8C',
        'empower-dark-gray': '#525252',
      },
      fontFamily: {
        'heading': ['Sports Invation', 'sans-serif'],
        'body': ['Balegare', 'system-ui', 'sans-serif'],
      },
      typography: {
        DEFAULT: {
          css: {
            color: '#1C1F4C',
            maxWidth: 'none',
            h1: {
              color: '#1C1F4C',
              fontWeight: '700',
              fontSize: '2.25rem',
              lineHeight: '2.5rem',
              marginTop: '0',
              marginBottom: '1.5rem',
            },
            h2: {
              color: '#1C1F4C',
              fontWeight: '600',
              fontSize: '1.875rem',
              lineHeight: '2.25rem',
              marginTop: '2rem',
              marginBottom: '1rem',
            },
            h3: {
              color: '#1C1F4C',
              fontWeight: '600',
              fontSize: '1.5rem',
              lineHeight: '2rem',
              marginTop: '1.5rem',
              marginBottom: '0.75rem',
            },
            h4: {
              color: '#1C1F4C',
              fontWeight: '600',
              fontSize: '1.25rem',
              lineHeight: '1.75rem',
              marginTop: '1.25rem',
              marginBottom: '0.5rem',
            },
            p: {
              marginTop: '1.25rem',
              marginBottom: '1.25rem',
              lineHeight: '1.75',
            },
            strong: {
              color: '#1C1F4C',
              fontWeight: '600',
            },
            em: {
              color: '#8C8C8C',
              fontStyle: 'italic',
            },
            blockquote: {
              borderLeftWidth: '4px',
              borderLeftColor: '#FF7F50',
              backgroundColor: 'rgba(232, 232, 232, 0.3)',
              paddingLeft: '1rem',
              paddingTop: '0.5rem',
              paddingBottom: '0.5rem',
              marginTop: '1.5rem',
              marginBottom: '1.5rem',
              fontStyle: 'italic',
              color: '#8C8C8C',
              borderTopRightRadius: '0.5rem',
              borderBottomRightRadius: '0.5rem',
              quotes: 'none',
            },
            'blockquote::before': {
              content: 'none',
            },
            'blockquote::after': {
              content: 'none',
            },
            ul: {
              marginTop: '1.25rem',
              marginBottom: '1.25rem',
            },
            ol: {
              marginTop: '1.25rem',
              marginBottom: '1.25rem',
            },
            li: {
              marginTop: '0.5rem',
              marginBottom: '0.5rem',
            },
            a: {
              color: '#FF7F50',
              textDecoration: 'underline',
              textDecorationColor: '#FF7F50',
              textUnderlineOffset: '2px',
              '&:hover': {
                color: '#E06A3D',
                textDecorationColor: '#E06A3D',
              },
            },
            code: {
              color: '#FF7F50',
              backgroundColor: '#F8F9FA',
              padding: '0.125rem 0.25rem',
              borderRadius: '0.25rem',
              fontSize: '0.875em',
              fontWeight: '500',
            },
            pre: {
              backgroundColor: '#1C1F4C',
              color: '#FFFFFF',
              padding: '1rem',
              borderRadius: '0.5rem',
              overflow: 'auto',
            },
            'pre code': {
              backgroundColor: 'transparent',
              padding: '0',
              color: 'inherit',
            },
          },
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
  safelist: [
    'bg-gradient-to-br',
    'bg-gradient-to-r',
    'bg-gradient-to-b',
    'from-empower-coral',
    'to-empower-lilac',
    'from-empower-lilac',
    'to-empower-coral',
    'from-empower-navy',
    'to-empower-navy',
    'bg-empower-coral',
    'bg-empower-lilac',
    'bg-empower-navy',
    'bg-empower-light-gray',
    'bg-empower-mid-gray',
    'bg-empower-dark-gray',
    'text-empower-coral',
    'text-empower-lilac',
    'text-empower-navy',
    'text-empower-light-gray',
    'text-empower-mid-gray',
    'text-empower-dark-gray',
    'section-gradient',
    'section-navy',
    'card-gradient',
    'btn-primary',
    'btn-secondary',
    'btn-outline',
    'text-gradient',
    'gradient-coral',
    'gradient-lilac',
    'gradient-navy',
    'gradient-hero',
    'glass',
    'glass-dark',
    'line-clamp-3',
  ],
} 